meta:
  title: Checkout API Reference (POC)
  description: The best API documentation generator ever.
  siteUrl: https://portal-demo.redoc.ly
headerIcon: ./assets/images/logo.svg
enableToc: true
oasDefinitions:
  checkout: ./developer-portal/api/swagger.yaml

stylesheets:
  - ./assets/global.css
ga:
  trackingId: UA-83886670-8
scripts:
  - ./scripts/hotjar.js

nav:
  - search: true
  - label: Log in
    page: developer-portal/index.mdx

  - label: Get test account
    href: https://checkout.com/get-test-account
